//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  question: Question;
  questionConnection: QuestionConnection;
  home: Home;
  homeConnection: HomeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryQuestionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryQuestionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuestionFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};

export type DocumentFilter = {
  question?: InputMaybe<QuestionFilter>;
  home?: InputMaybe<HomeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Question | Home | Folder;

export type QuestionStats = {
  __typename?: 'QuestionStats';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type Question = Node & Document & {
  __typename?: 'Question';
  category: Scalars['String']['output'];
  title: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  author: Scalars['String']['output'];
  role: Scalars['String']['output'];
  votes: Scalars['String']['output'];
  answers: Scalars['Float']['output'];
  pageTitle: Scalars['String']['output'];
  pageDescription: Scalars['String']['output'];
  lead: Scalars['String']['output'];
  stats?: Maybe<Array<Maybe<QuestionStats>>>;
  whyNowTitle: Scalars['String']['output'];
  whyNowText: Scalars['String']['output'];
  topics?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  answerTitle: Scalars['String']['output'];
  summary?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  relatedSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type QuestionStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type QuestionFilter = {
  category?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  votes?: InputMaybe<StringFilter>;
  answers?: InputMaybe<NumberFilter>;
  pageTitle?: InputMaybe<StringFilter>;
  pageDescription?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  stats?: InputMaybe<QuestionStatsFilter>;
  whyNowTitle?: InputMaybe<StringFilter>;
  whyNowText?: InputMaybe<StringFilter>;
  topics?: InputMaybe<StringFilter>;
  answerTitle?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  relatedSlugs?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type QuestionConnectionEdges = {
  __typename?: 'QuestionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Question>;
};

export type QuestionConnection = Connection & {
  __typename?: 'QuestionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<QuestionConnectionEdges>>>;
};

export type HomeEditorialPicks = {
  __typename?: 'HomeEditorialPicks';
  label: Scalars['String']['output'];
  slug: Scalars['String']['output'];
};

export type Home = Node & Document & {
  __typename?: 'Home';
  featuredQuestionSlugs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  heroFeaturedSlug: Scalars['String']['output'];
  editorialPicks?: Maybe<Array<Maybe<HomeEditorialPicks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeEditorialPicksFilter = {
  label?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  featuredQuestionSlugs?: InputMaybe<StringFilter>;
  heroFeaturedSlug?: InputMaybe<StringFilter>;
  editorialPicks?: InputMaybe<HomeEditorialPicksFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateQuestion: Question;
  createQuestion: Question;
  updateHome: Home;
  createHome: Home;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateQuestionArgs = {
  relativePath: Scalars['String']['input'];
  params: QuestionMutation;
};


export type MutationCreateQuestionArgs = {
  relativePath: Scalars['String']['input'];
  params: QuestionMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};

export type DocumentUpdateMutation = {
  question?: InputMaybe<QuestionMutation>;
  home?: InputMaybe<HomeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  question?: InputMaybe<QuestionMutation>;
  home?: InputMaybe<HomeMutation>;
};

export type QuestionStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type QuestionMutation = {
  category?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  votes?: InputMaybe<Scalars['String']['input']>;
  answers?: InputMaybe<Scalars['Float']['input']>;
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageDescription?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<QuestionStatsMutation>>>;
  whyNowTitle?: InputMaybe<Scalars['String']['input']>;
  whyNowText?: InputMaybe<Scalars['String']['input']>;
  topics?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  answerTitle?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  relatedSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomeEditorialPicksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  featuredQuestionSlugs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  heroFeaturedSlug?: InputMaybe<Scalars['String']['input']>;
  editorialPicks?: InputMaybe<Array<InputMaybe<HomeEditorialPicksMutation>>>;
};

export type QuestionPartsFragment = { __typename: 'Question', category: string, title: string, excerpt: string, author: string, role: string, votes: string, answers: number, pageTitle: string, pageDescription: string, lead: string, whyNowTitle: string, whyNowText: string, topics?: Array<string | null> | null, answerTitle: string, summary?: Array<string | null> | null, relatedSlugs?: Array<string | null> | null, body?: any | null, stats?: Array<{ __typename: 'QuestionStats', value: string, label: string } | null> | null };

export type HomePartsFragment = { __typename: 'Home', featuredQuestionSlugs?: Array<string | null> | null, heroFeaturedSlug: string, editorialPicks?: Array<{ __typename: 'HomeEditorialPicks', label: string, slug: string } | null> | null };

export type QuestionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type QuestionQuery = { __typename?: 'Query', question: { __typename: 'Question', id: string, category: string, title: string, excerpt: string, author: string, role: string, votes: string, answers: number, pageTitle: string, pageDescription: string, lead: string, whyNowTitle: string, whyNowText: string, topics?: Array<string | null> | null, answerTitle: string, summary?: Array<string | null> | null, relatedSlugs?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'QuestionStats', value: string, label: string } | null> | null } };

export type QuestionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuestionFilter>;
}>;


export type QuestionConnectionQuery = { __typename?: 'Query', questionConnection: { __typename?: 'QuestionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'QuestionConnectionEdges', cursor: string, node?: { __typename: 'Question', id: string, category: string, title: string, excerpt: string, author: string, role: string, votes: string, answers: number, pageTitle: string, pageDescription: string, lead: string, whyNowTitle: string, whyNowText: string, topics?: Array<string | null> | null, answerTitle: string, summary?: Array<string | null> | null, relatedSlugs?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'QuestionStats', value: string, label: string } | null> | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, featuredQuestionSlugs?: Array<string | null> | null, heroFeaturedSlug: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, editorialPicks?: Array<{ __typename: 'HomeEditorialPicks', label: string, slug: string } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, featuredQuestionSlugs?: Array<string | null> | null, heroFeaturedSlug: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, editorialPicks?: Array<{ __typename: 'HomeEditorialPicks', label: string, slug: string } | null> | null } | null } | null> | null } };

export const QuestionPartsFragmentDoc = gql`
    fragment QuestionParts on Question {
  __typename
  category
  title
  excerpt
  author
  role
  votes
  answers
  pageTitle
  pageDescription
  lead
  stats {
    __typename
    value
    label
  }
  whyNowTitle
  whyNowText
  topics
  answerTitle
  summary
  relatedSlugs
  body
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  featuredQuestionSlugs
  heroFeaturedSlug
  editorialPicks {
    __typename
    label
    slug
  }
}
    `;
export const QuestionDocument = gql`
    query question($relativePath: String!) {
  question(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...QuestionParts
  }
}
    ${QuestionPartsFragmentDoc}`;
export const QuestionConnectionDocument = gql`
    query questionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: QuestionFilter) {
  questionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...QuestionParts
      }
    }
  }
}
    ${QuestionPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      question(variables: QuestionQueryVariables, options?: C): Promise<{data: QuestionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuestionQueryVariables, query: string}> {
        return requester<{data: QuestionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuestionQueryVariables, query: string}, QuestionQueryVariables>(QuestionDocument, variables, options);
      },
    questionConnection(variables?: QuestionConnectionQueryVariables, options?: C): Promise<{data: QuestionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuestionConnectionQueryVariables, query: string}> {
        return requester<{data: QuestionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuestionConnectionQueryVariables, query: string}, QuestionConnectionQueryVariables>(QuestionConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4002/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  